version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gohaul?schema=public
      JWT_SECRET: your_jwt_secret_here
      NODE_ENV: development
      PORT: "3000"
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
      - "3001:3001"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gohaul
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: 